spring:
  datasource:
    url: jdbc:h2:file:./build/h2/db/course-catalog;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: some-password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true

message: hello from local profile
