message: hello from prod profile
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course_catalog
    driver-class-name: org.postgresql.Driver
    username: sa
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
